apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-config
  namespace: training1
data:
  name: "Hello Minny"
  {{- with .Values.hobbies }}
  music: {{ .music | upper }}
  movie: {{ .movie | upper }}
  {{- end }}
  lists: |-
    {{- range .Values.moviesList }}
      {{ . | upper | quote }}
    {{- end }}
